blank_issues_enabled: false
contact_links:
  - name: ❓ 讨论、问答和非项目问题 (Discussions, questions, and non-project issues)
    url: https://jq.qq.com/?_wv=1027&k=I1oJKSTH
    about: 其他不明之处，请移步我们的QQ群 12370907 (For other unclear things, please move to our qq group 12370907)