name: Welcome
on:
  pull_request:
    types: [ opened, closed ]
  issues:
    types: [ opened ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          FIRST_ISSUE: |
            Hi @{{ author }} ğŸ‘‹

            Thanks for opening this issue to HaoZi Panel, we will respond as soon as possible! ğŸ’–
            æ„Ÿè°¢æ‚¨å‘ è€—å­é¢æ¿ æå‡ºæ­¤ Issueï¼Œæˆ‘ä»¬å°†å°½å¿«åé¦ˆï¼ ğŸ’–

          FIRST_PR: |
            Hi @{{ author }} ğŸ‘‹

            Thanks for opening this PR to HaoZi Panel, But we use JiHu GitLab to develop, please submit PR to our JiHu GitLab repository, thank you! ğŸ’–
            æ„Ÿè°¢æ‚¨å‘ è€—å­é¢æ¿ æäº¤æ­¤ PRï¼Œä½†æ˜¯æˆ‘ä»¬ä½¿ç”¨ æç‹GitLab è¿›è¡Œå¼€å‘ï¼Œè¯·æäº¤ PR åˆ°æˆ‘ä»¬çš„ æç‹GitLab ä»“åº“ï¼Œè°¢è°¢ï¼ ğŸ’–

          STAR_MESSAGE: |
            If you like this project, please â­starâ­ our repository to support us!
            å¦‚æœæ‚¨å–œæ¬¢è¿™ä¸ªé¡¹ç›®ï¼Œè¯· Star ä»“åº“ç»™äºˆæˆ‘ä»¬æ”¯æŒï¼
